### ISSUE TITLE
CIGs generation optimal parameters

### ISSUE THREAD

**Issue by advaitb** [slimgroup/WISE.jl#1]
Hi,

I'm trying to generate CIGs from SEG Salt data using your script. Here are the true and smoothed velocity models I'm working with: 
![velocity_1](https://github.com/slimgroup/WISE.jl/assets/13657575/d3d75bc0-d83f-4d1e-9f29-0f3b7b495ea0)

I ran the script with 64 sources and 210 receivers with the noise added and got this:
![CIGs_1_swap](https://github.com/slimgroup/WISE.jl/assets/13657575/44f45b3c-87bf-4860-b63c-c35a240aa025)

Without noise I get this:
![CIGs_1_improved](https://github.com/slimgroup/WISE.jl/assets/13657575/93c125b8-3efa-49a5-8e81-dc3f388cd42c)

If I explicitly remove noise and the wb parameter to space out the sources and receivers I get this:
![CIGs_explicit](https://github.com/slimgroup/WISE.jl/assets/13657575/253b5681-ec1a-4ac9-b301-adff4879d60e)

The code I ran for the without noise case is [here](https://gist.github.com/advaitb/927030a23c743f05f79aababdef9e879). What would be the best wat to generate CIGs from this data?

**Comment by ziyiyin97** [comment]
Hi,

Thanks for your interest and your thorough explanation of the issue! I suggest you carry out the following steps:

1. It seems like your experiments end up being a transmission seismic instead of reflection. I think this line https://gist.github.com/advaitb/927030a23c743f05f79aababdef9e879#file-sscig-jl-L68 was set up in a wrong way because `wb` stands for the position of the water bottom in grids. By looking at your model on the top, it seems like 10-ish. I would make sure that your sources and receivers are on the top of the model.
2. This can also be verified if you look at the generated data https://gist.github.com/advaitb/927030a23c743f05f79aababdef9e879#file-sscig-jl-L102 and see if they look good. By looking at the data, you could also figure out how long you want to record -- now you set up 4000ms recording https://gist.github.com/advaitb/927030a23c743f05f79aababdef9e879#file-sscig-jl-L60. Typically I would record until the full turning wave shows up in the shot record with longest offset. On top of these, a 25 Hz wavelet seems to be a bit high for 12.5m discretization if I read these correctly from your file. You could check whether there is numerical dispersion in your generated data.
3. Next, I would compute a reverse-time migration (RTM), which happens to be the CIG at zero-offset. You can try `isic = true` in this line https://gist.github.com/advaitb/927030a23c743f05f79aababdef9e879#file-sscig-jl-L83 to get rid of some of the tomographic artifacts. You would expect a good looking sharp image when you do no noise and use good migration velocity.
4. Finally, we can proceed to CIGs. -40m to 40m offset seems to be very short. In the experiment of https://arxiv.org/abs/2401.06230, I used -500m to 500m offset for a 3km-ish deep model. I would try on the same orders of magnitude for your models.

**Comment by ziyiyin97** [comment]
Close for now but feel free to reopen.
